apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-auth
  labels:
    run: diplomska
spec:
  selector:
    matchLabels:
      run: diplomska
  replicas: 2
  template:
    metadata:
      labels:
        run: diplomska
    spec:
      containers:
        - name: auth
          image: velikovp/auth-ms
          ports:
          - containerPort: 3307
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: autoscaler-auth
  labels:
    run: diplomska
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dep-auth
  minReplicas: 2
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-auth
  labels:
    run: diplomska
spec:
  ports:
    - port: 3307
      targetPort: 3307
      protocol: TCP
  selector:
    run: diplomska
  type: LoadBalancer