apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  selector:
    matchLabels:
      run: diplomska
  replicas: 1
  template:
    metadata:
      labels:
        run: diplomska
    spec:
      containers:
        - name: database
          image: mysql/mysql-server
          imagePullPolicy: Never
          ports:
          - containerPort: 3306
# TODO SETUP THE CORRECT ENVs
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_USER
              value: "user"
            - name: MYSQL_PASSWORD
              value: "pass"
            - name: MYSQL_DATABASE
              value: "db_diplomska"
---
apiVersion: v1
kind: Service
metadata:
  name: db-service
  labels:
    run: diplomska
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    run: diplomska