apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-executor
  labels:
    run: diplomska
spec:
  selector:
    matchLabels:
      run: diplomska
  replicas: 3
  template:
    metadata:
      labels:
        run: diplomska
    spec:
      containers:
        - name: executor
          image: velikovp/executor-ms
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: load-balancer-executor
  labels:
    run: diplomska
spec:
  ports:
    - port: 3308
      targetPort: 3308
      protocol: TCP
  selector:
    run: diplomska
  type: LoadBalancer