apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-db
  labels:
    run: diplomska
spec:
  selector:
    matchLabels:
      run: diplomska
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        run: diplomska
    spec:
      containers:
        - name: database
          image: mysql:5.6
          ports:
          - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db-root
                  key: password
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: secret-db-user
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret-db-user
                  key: password
            - name: MYSQL_DATABASE
              value: "db_diplomska"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim