apiVersion: v1
kind: ConfigMap
metadata:
  name: config-auth
data:
  application.properties: |-
    spring.datasource.platform=mysql
    spring.datasource.url=jdbc:mysql://svc-db.default.svc.cluster.local:3306/db_diplomska
    spring.jpa.hibernate.ddl-auto=create-drop
    spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
    spring.datasource.username=${MYSQL_USERNAME}
    spring.datasource.password=${MYSQL_PASSWORD}
    jwt.token.secret=${JWT_SECRET}
    server.port=3307