apiVersion: v1
kind: Service
metadata:
  name: load-balancer-auth
  labels:
    run: diplomska
spec:
  ports:
    - port: 3307
      targetPort: 3307
      protocol: TCP
  selector:
    run: diplomska
  type: LoadBalancer