apiVersion: v1
kind: Service
metadata:
  name: load-balancer-executor
  labels:
    run: diplomska
spec:
  ports:
    - port: 3308
      targetPort: 3308
      protocol: TCP
  selector:
    run: diplomska
  type: LoadBalancer